---
title: "A Simple Daily Water Balance Simulation"
author: "D.E. Beaudette and J.M. Skovlin"
date: "`r Sys.Date()`"
output:
  html_document:
    mathjax: null
    jquery: null
    smart: no
    keep_md: no
---
  
```{r setup, echo=FALSE, results='hide', warning=FALSE}
# setup
library(knitr, quietly=TRUE)
opts_chunk$set(message=FALSE, warning=FALSE, background='#F7F7F7', fig.align='center', fig.retina=2, dev='png', tidy=FALSE, verbose=FALSE)
options(width=100, stringsAsFactors=FALSE, cache=TRUE)
```

## Setup
You will need these packages.
```{r}
library(daymetr)
library(Evapotranspiration)
library(elevatr)
library(zoo)

library(aqp)
library(soilDB)
library(sharpshootR)

library(sf)

library(pbapply)
library(reshape2)

library(latticeExtra)
library(tactile)
library(knitr)
library(RColorBrewer)
library(viridis)

# special installation instructions:
# https://github.com/josephguillaume/hydromad#installation
library(hydromad)
```

```{r fig.width=8, fig.height=6}
## simulate NULL PET
# near Sonora, CA
p <- data.frame(
  x = -120.37673,
  y = 37.99877
)
p <- st_as_sf(p, coords = c('x', 'y'))
st_crs(p) <- 4326
daily.data <- prepareDailyClimateData(p, start = 2013, end = 2014, onlyWB = TRUE)

# save PET
daily.data$PET_saved <- daily.data$PET

# example soil material
data("ROSETTA.centroids")
vars <- c('texture', 'sat', 'fc', 'pwp')

# required soil hydraulic parameters + ID
x <- ROSETTA.centroids[c(12, 1, 3, 5), vars]

# thickness and recession coef.
x$thickness <- 50

# recession coef.
x$a.ss <- c(0.1, 0.1, 0.1, 0.1)
x

# NO PET
daily.data$PET <- 0

z <- dailyWB(x, daily.data, id = 'texture', S_0 = 1)

xyplot(
  VWC ~ date, 
  groups = texture, 
  data = z, 
  type = 'l', 
  par.settings = tactile.theme(), 
  auto.key = list(lines = TRUE, points = FALSE, columns = 4), 
  panel = function(...) {
    panel.xyplot(...)
    panel.abline(h = (x$fc), col = tactile.theme()$superpose.line$col, lty = 2)
  })


daily.data$PET <- daily.data$PET_saved

z <- dailyWB(x, daily.data, id = 'texture', S_0 = 1)

xyplot(
  VWC ~ date, 
  groups = texture, 
  data = z, 
  type = 'l', 
  par.settings = tactile.theme(), 
  auto.key = list(lines = TRUE, points = FALSE, columns = 4), 
  panel = function(...) {
    panel.xyplot(...)
    panel.abline(h = x$fc, col = tactile.theme()$superpose.line$col, lty = 2)
  })
```


```{r fig.width=8, fig.height=6}
## prepare some example data via DAYMET

# near Sonora, CA
p <- data.frame(
  x = -120.37673,
  y = 37.99877
)
p <- st_as_sf(p, coords = c('x', 'y'))
st_crs(p) <- 4326

daily.data <- prepareDailyClimateData(p, start = 2000, end = 2019, onlyWB = TRUE)

head(daily.data)


# example soil material
data("ROSETTA.centroids")
vars <- c('texture', 'sat', 'fc', 'pwp')

# required soil hydraulic parameters + ID
x <- ROSETTA.centroids[c(12, 1, 3, 5), vars]

# thickness and recession coef.
x$thickness <- 50
# this should reflect drainage class: lower numbers = less internal drainage
x$a.ss <- c(0.1, 0.1, 0.1, 0.1)

# x$a.ss <- 0.3
x

## much slower with current R-based implementation
z <- dailyWB(x, daily.data, id = 'texture', MS.style = 'newhall')

str(z)

ann.AET <- tapply(
  z$ET, INDEX = list(z$texture, z$year), FUN = sum
)

t(apply(ann.AET, 1, quantile))


kable(prop.table(table(z$texture, z$state), margin = 1), digits = 2)

# kable(prop.table(table(z$texture, z$state <= 'dry'), margin = 1), digits = 2)
# kable(prop.table(table(z$texture, z$state > 'very moist'), margin = 1), digits = 2)



xyplot(
  VWC ~ date, 
  groups = texture, 
  data = z, 
  type = 'l', 
  par.settings = tactile.theme(), 
  auto.key = list(lines = TRUE, points = FALSE, columns = 4), 
  subset = year %in% c('2013'), 
  panel = function(...) {
    panel.xyplot(...)
    panel.abline(h = x$fc, col = tactile.theme()$superpose.line$col, lty = 2)
  })

xyplot(S ~ date, groups = texture, data = z, type = c('l', 'g'), par.settings = tactile.theme(), auto.key = list(lines = TRUE, points = FALSE, columns = 4), subset = year %in% c('2013'))

xyplot(U ~ date | texture, data = z, type = c('l', 'g'), par.settings = tactile.theme(), auto.key = list(lines = TRUE, points = FALSE, columns = 3), subset = year %in% c('2013'))





#
msp <- moistureStateProportions(z, id = 'texture', step = 'week')

# colors / style
ll <- levels(msp$state)
n.states <- length(ll)
ms.colors <- brewer.pal(n.states, 'Spectral')

suppressWarnings(
  trellis.par.set(list(superpose.polygon=list(col=ms.colors, border=ms.colors)))
)

sK <- simpleKey(text = ll, space='top', columns=n.states, rectangles = TRUE, points=FALSE, cex=1)

levelplot(state ~ as.numeric(doy) * texture | year, data = z, 
          subset = year %in% c('2013'),
          col.regions = colorRampPalette(brewer.pal(n.states, 'Spectral'), interpolate = 'spline', space = 'Lab'),
          par.settings = tactile.theme(),
          as.table = TRUE,
          key = sK,
          colorkey = FALSE,
          xlab = 'Day of the Year',
          ylab = '',
          main='Soil Moisture State',
          scales=list(alternating = 1, x=list(tick.number=25))
)
```

```{r fig.width=9, fig.height=8}
levelplot(state ~ as.numeric(doy) * year | texture, data = z, 
          # subset = year %in% c('2010'),
          col.regions = colorRampPalette(brewer.pal(n.states, 'Spectral'), interpolate = 'spline', space = 'Lab'),
          par.settings = tactile.theme(),
          as.table = TRUE,
          key = sK,
          colorkey = FALSE,
          xlab = 'Day of the Year',
          ylab = '',
          main='Soil Moisture State',
          scales=list(alternating = 1, y = list(cex = 0.75), x = list(tick.number=20, cex = 0.66))
)

levelplot(S ~ as.numeric(doy) * year | texture, data = z, 
          # subset = year %in% c('2010'),
          col.regions = colorRampPalette(brewer.pal(n.states, 'Spectral'), interpolate = 'spline', space = 'Lab'),
          par.settings = tactile.theme(),
          as.table = TRUE,
          xlab = 'Day of the Year',
          ylab = '',
          main='Soil Moisture\nEffective Depth (mm)',
          scales=list(alternating = 1, x=list(tick.number=25))
)

levelplot(VWC ~ as.numeric(doy) * year | texture, data = z, 
          # subset = year %in% c('2010'),
          col.regions = colorRampPalette(brewer.pal(n.states, 'Spectral'), interpolate = 'spline', space = 'Lab'),
          par.settings = tactile.theme(),
          as.table = TRUE,
          xlab = 'Day of the Year',
          ylab = '',
          main='Soil Moisture\nVolumetric Water Content',
          scales=list(alternating = 1, x=list(tick.number=25))
)

levelplot(ET ~ as.numeric(doy) * year | texture, data = z, 
          # subset = year %in% c('2010'),
          col.regions = colorRampPalette(brewer.pal(n.states, 'Spectral'), interpolate = 'spline', space = 'Lab'),
          par.settings = tactile.theme(),
          as.table = TRUE,
          xlab = 'Day of the Year',
          ylab = '',
          main='AET',
          scales=list(alternating = 1, x=list(tick.number=25))
)
```
## 

```{r fig.width=8, fig.height=6}
barchart(proportion ~ interval | texture, groups = state, 
         main='Expected Weekly Soil Moisture State\nDAYMET 2000-2019',
         data = msp, horiz = FALSE, stack = TRUE, xlab = '', ylab='Proportion',
         as.table=TRUE,
         box.ratio = 30,
         key=sK,
         strip=strip.custom(bg=grey(0.9)),
         par.strip.text=list(cex=1.25),
         scales=list(y=list(alternating=3, cex=1), x=list(draw = FALSE)),
         par.settings = list(
           superpose.polygon = list(
             col = ms.colors, lwd = 1, lend = 1
           )
         ),
         # this breaks auto.key, thus requires simpleKey()
         panel=function(...) {
           # panel.abline(h=seq(0, 1, by=0.1), v=1:52, col=grey(0.9))
           panel.barchart(...)
         }
)


mss <- moistureStateStats(msp, id = 'texture')

xyplot(H ~ as.numeric(interval), groups = texture, data = mss, type = c('l', 'g'), par.settings = tactile.theme(), auto.key = list(lines = TRUE, points = FALSE, columns = 4))

levelplot(state ~ as.numeric(interval) * texture, data = mss, 
          # subset = year %in% c('2010'),
          col.regions = colorRampPalette(brewer.pal(n.states, 'Spectral'), interpolate = 'spline', space = 'Lab'),
          par.settings = tactile.theme(),
          as.table = TRUE,
          key = sK,
          colorkey = FALSE,
          xlab = 'Week',
          ylab = '',
          main='Soil Moisture',
          scales=list(alternating = 1, x=list(tick.number=25))
)

##

# probability that soil is <= dry moisture state
mst <- moistureStateThreshold(z, id = 'texture', threshold = 'dry', operator = '<=')
str(mst)

# colors / style
stripe.colors <- colorRampPalette(viridis(100), interpolate = 'spline', space = 'Lab')

levelplot(Pr ~ as.numeric(doy) * texture, data = mst, 
          col.regions = stripe.colors,
          par.settings = tactile.theme(),
          xlab = 'Day of the Year',
          ylab = '',
          main='Pr(Soil at Field Capacity or Drier)\nDAYMET 2000-2019',
          scales=list(x=list(tick.number=25))
)



# a different take: "on average, when do the soils
xyplot(Pr ~ as.numeric(doy), groups = texture,
       main='Pr(Soil at Field Capacity or Drier)\nDAYMET 2000-2019',
       data = mst, type=c('l', 'g'),
       xlab = '', ylab='Probability',
       as.table=TRUE,
       auto.key=list(lines=TRUE, points=FALSE, columns=length(levels(msp$texture))),
       strip=strip.custom(bg=grey(0.9)),
       par.strip.text=list(cex=1.25),
       scales=list(y=list(alternating=3, cex=1), x=list(relation='free', alternating=1, cex=0.85, rot=0)),
       par.settings = tactile.theme(superpose.line = list(lwd = 2))
)


## hmmm
tapply(mst$Pr, mst$texture, function(i) length(which(i > 0.8)))
```
