## you will need the bleeding-edge version of aqp and sharpshootR
## get like this
#
## stable versions + deps
# install.packages('aqp', dep=TRUE)
# install.packages('sharpshootR', dep=TRUE)
# 
## latest versions
# devtools::install_github("ncss-tech/aqp", dependencies=FALSE, upgrade_dependencies=FALSE)
# devtools::install_github("ncss-tech/sharpshootR", dependencies=FALSE, upgrade_dependencies=FALSE)
#

library(aqp)
library(soilDB)
library(sharpshootR)
library(cluster)
library(RColorBrewer)

# sample data
data("loafercreek")

# get a subset of profiles to work with
x <- loafercreek[20:30, ]

# check rock fragment data
hist(x$total_frags_pct)

# check existing texture
table(x$texture_class)

# order field texture according to plant available water low -> high
# note: leaving out "in-lieu-of" texture classes for organic or bedrock
x$texture_class <- factor(x$texture_class, ordered = TRUE, levels = c('sl', 'scl', 'l', 'sil', 'c', 'sic', 'cl', 'sicl'))

# graphical check
par(mar=c(0,1,3,1))
plot(x, color='texture_class', label='pedon_id', col.palette=brewer.pal(10, 'Spectral'))
addVolumeFraction(x, 'total_frags_pct')

# make a fake name with texture class + RF volume:
x$fake.name <- ifelse(!is.na(x$texture_class), paste0(x$texture_class, ' - ', x$total_frags_pct),  '')
plot(x, color='texture_class', name='fake.name', label='pedon_id', cex.name=0.65, col.palette=brewer.pal(10, 'Spectral'))
addVolumeFraction(x, 'total_frags_pct')


# make an index to soil horizons (anything other than O|Cr|R)
idx <- grep('O|Cr|R', x$hzname, invert = TRUE)

# compute pair-wise distances using texture class (ordered factor) and rock frag volume
d <- profile_compare(x, vars=c('texture_class', 'total_frags_pct'), max_d=100, k=0, filter=idx, replace_na=TRUE, add_soil_flag=TRUE)
# divisive hierarchical clustering
dd <- diana(d)

# plot dendrogram + profiles
par(mar=c(2,1,3,1))
plotProfileDendrogram(x, dd, scaling.factor = 0.75, y.offset = 5, width=0.15, color='texture_class', name='fake.name', label='pedon_id', cex.name=0.75, col.palette=brewer.pal(10, 'Spectral'))
addVolumeFraction(x, 'total_frags_pct')


##
## do it again, this time using hz + site attributes (field slope + elevation)
##

# fix some missing data
x$elev_field[x$elev_field == 0] <- 380

# graphical check: order pedons by slope
par(mar=c(0,1,3,1))
plot(x, color='texture_class', label='pedon_id', col.palette=brewer.pal(10, 'Spectral'), plot.order=order(x$slope_field))
addVolumeFraction(x, 'total_frags_pct')
axis(side=1, at=1:length(x), labels=x$slope_field[order(x$slope_field)], line=-3)
mtext(text='Field Described Slope (%)', side=1, line=-4)

# graphical check: order pedons by elevation
par(mar=c(0,1,3,1))
plot(x, color='texture_class', label='pedon_id', col.palette=brewer.pal(10, 'Spectral'), plot.order=order(x$elev_field))
addVolumeFraction(x, 'total_frags_pct')
axis(side=1, at=1:length(x), labels=x$elev_field[order(x$elev_field)], line=-3)
mtext(text='Field Described Slope (m)', side=1, line=-4)



# compute pair-wise distances using:
# hz attributes: texture class (ordered factor) and rock frag volume
# site attributes: surface slope and elevation
d <- profile_compare(x, vars=c('texture_class', 'total_frags_pct', 'slope_field', 'elev_field'), max_d=100, k=0, filter=idx, replace_na=TRUE, add_soil_flag=TRUE)
# divisive hierarchical clustering
dd <- diana(d)

# plot dendrogram + profiles
par(mar=c(2,1,3,1))
plotProfileDendrogram(x, dd, scaling.factor = 0.008, y.offset = 0.05, width=0.15, color='texture_class', name='fake.name', label='pedon_id', cex.name=0.75, col.palette=brewer.pal(10, 'Spectral'))
addVolumeFraction(x, 'total_frags_pct')

