```{r setup, echo=FALSE, results='hide'}
# setup
opts_chunk$set(message=FALSE, warning=FALSE, background='#F7F7F7', dpi=100, fig.align='center', dev='CairoPNG', tidy=FALSE, verbose=FALSE)
options(width=100, stringsAsFactors=FALSE)
```

```{r prep-environment, results='hide'}
library(soilDB)

# filter function to ID components with non-overlapping restrictive features
f <- function(i) {
  h <- horizons(i) # extract horizons
  hd <- horizonDepths(i) # extract horizon depth column names
  # check: is the restrictive feature top depth in the set of horizon top depths?
  top.check <- i$resdept_r %in% h[, hd[1]]
  # check: is the restrictive feature bottom depth in the set of horizon bottom depths?
  bottom.check <- i$resdepb_r %in% h[, hd[2]]
  # check: missing restrictive feature bottom depth
  missing.res.bottom.check <- is.na(i$resdepb_r)
  
  # combine tests into string: xyz --> top check | bottom check | missing res. bottom
  res <- paste(as.numeric(c(top.check, bottom.check, missing.res.bottom.check)), collapse='')
  
  # done, return results
  return(res)
}
```

```{r SDA-queries, results='hide'}
# query official data
# note SQL BS required to get SSURGO-style cokey values

# component / horizon data associated with components that have duripans
q.1 <- "SELECT CAST(mapunit.mukey as varchar) + ':' + CAST(component.cokey as varchar) as cokey, hzname, hzdept_r, hzdepb_r
FROM legend
JOIN mapunit ON mapunit.lkey = legend.lkey
JOIN component ON component.mukey = mapunit.mukey
JOIN chorizon ON component.cokey = chorizon.cokey
JOIN corestrictions ON chorizon.cokey = corestrictions.cokey
WHERE legend.areasymbol IN ('ca013','ca031','ca067','ca077','ca095','ca609','ca624','ca628','ca632','ca642','ca644','ca647','ca648','ca649','ca651','ca653','ca654','ca659','ca660','ca101','ca011','ca021','ca612','ca668','ca666','ca113')
AND reskind = 'Duripan'
ORDER BY chorizon.cokey, hzdept_r ASC;"

# just restrictive feature information
q.2 <- "SELECT CAST(mapunit.mukey as varchar) + ':' + CAST(component.cokey as varchar) as cokey, resdept_r, resdepb_r, reskind
FROM legend
JOIN mapunit ON mapunit.lkey = legend.lkey
JOIN component ON component.mukey = mapunit.mukey
JOIN corestrictions ON component.cokey = corestrictions.cokey
WHERE legend.areasymbol IN ('ca013','ca031','ca067','ca077','ca095','ca609','ca624','ca628','ca632','ca642','ca644','ca647','ca648','ca649','ca651','ca653','ca654','ca659','ca660','ca101','ca011','ca021','ca612','ca668','ca666','ca113')
AND reskind = 'Duripan'
ORDER BY component.cokey;"

# send queries to SDA
x <- SDA_query(q.1)
y <- SDA_query(q.2)
```

```{r check-data, fig.width=10}
# check: are there >1 restrictions / cokey?
t.cokey <- table(y$cokey)
problem.cokey <- names(t.cokey)[which(t.cokey > 1)]

# print data associated with multiple duripan / component
# ... how did this happen?
y[y$cokey %in% problem.cokey, ]

# promote to SPC
depths(x) <- cokey ~ hzdept_r + hzdepb_r

# merge-in restriction data, minus the problem records
site(x) <- y[! y$cokey %in% problem.cokey, ]


# subset and visually check
par(mar=c(0,0,0,0))
s <- x[1:20, ]
plot(s)
addBracket(top=s$resdept_r, bottom=s$resdepb_r, col='red', offset=0.01, lwd=2, tick.length=0)


# apply filter function and save as site-level data
x$res_check <- profileApply(x, f)

# decode via factor levels
x$res_check <- factor(x$res_check, 
  levels=c('000', '001', '010', '011', '100', '101', '110', '111'), 
  labels=c('no overlap', 'res. missing bottom', 'top error', 'top error|res. missing bottom', 'bottom error', 'bottom error|res. missing bottom', 'perfect overlap', 'top overlap|restriction missing bottom depth'))

# tabulate: yikes!
as.data.frame(table(x$res_check))

# get those components with exact overlap
s <- x[which(x$res_check == 'perfect overlap'), ]
ss <- s[1:40, ]
plot(ss)
addBracket(top=ss$resdept_r, bottom=ss$resdepb_r, col='red', offset=0.01, lwd=2, tick.length=0)


# get those components with top errors
s.bad <- x[which(x$res_check == 'top error'), ]
plot(s.bad)
addBracket(top=s.bad$resdept_r, bottom=s.bad$resdepb_r, col='red', offset=0.01, lwd=2, tick.length=0)


# get those components with bottom errors
s.bad <- x[which(x$res_check == 'bottom error'), ]
plot(s.bad)
addBracket(top=s.bad$resdept_r, bottom=s.bad$resdepb_r, col='red', offset=0.01, lwd=2, tick.length=0)


# get those components with no overlap
s.bad <- x[which(x$res_check == 'no overlap'), ]
plot(s.bad)
addBracket(top=s.bad$resdept_r, bottom=s.bad$resdepb_r, col='red', offset=0.01, lwd=2, tick.length=0)

```

