---
title: "gNATSGO / gSSURGO Web Coverage Service"
author: "D.E. Beaudette"
date: "`r Sys.Date()`"
output:
  html_document:
    mathjax: null
    jquery: null
    smart: no
    number_sections: yes
    toc: yes
    toc_depth: 3
    toc_float:
      collapsed: true
      smooth_scroll: false
---
  
  
```{r setup, echo=FALSE, results='hide', warning=FALSE}
# setup
library(knitr, quietly=TRUE)
library(kableExtra, quietly=TRUE)
opts_chunk$set(message=FALSE, warning=FALSE, background='#F7F7F7', fig.align='center', fig.retina=2, dev='png', tidy=FALSE, verbose=FALSE)
options(width=100, stringsAsFactors=FALSE)
```

# Introduction


## Setup


```{r eval = FALSE}
remotes::install_github("ncss-tech/soilDB", dependencies = FALSE, upgrade = FALSE, build = FALSE)
```


## Grid Selection
```{r eval = FALSE}
x <- mukey.wcs(var = 'gSSURGO', aoi = c(-114.16, 47.65, -114.08, 47.68))

x <- mukey.wcs(var = 'gNATSGO', aoi = c(-114.16, 47.65, -114.08, 47.68))
```

## Caveats / Limitations

```{r eval = FALSE}


```


# A Simple Demonstration

```{r}
# latest from GitHub
library(soilDB)

# wrangling polygons and CRS transformations
library(sp)
library(rgdal)

# geometric calculations
library(rgeos)

# raster data visualization
library(raster)
library(rasterVis)
library(viridis)


# AOI corners in WGS84 GCS
# xmin, ymin, xmax, ymax
a <- c(-114.16, 47.65, -114.08, 47.68)

# too big for SDA geometry (>32Mb WKT serialization)
# a <- c(-114.5, 47, -114, 47.5)

# fetch gNATSGO map unit keys at native resolution
x <- mukey.wcs(var = 'gSSURGO', aoi = a)

# fetch gSSURGO map unit keys at native resolution 
# x <- mukey.wcs(var = 'gssurgo', aoi = a)

# OK
levelplot(
  x, 
  att = 'ID',
  main = 'gSSURGO map unit keys',
  margin = FALSE, 
  colorkey = FALSE, 
  col.regions = viridis
  )
```

## BBOX Specification


## Grid Resolution Specification


## Fetching Polygons from SDA
```{r}
# convert raster extent into vector 
g <- as(extent(x), 'SpatialPolygons')
proj4string(g) <- projection(x)

# get intersecting SSURGO linework as SpatialPolygonsDataFrame from SDA
p <- SDA_spatialQuery(g, what = 'geom', geomIntersection = TRUE)

# transform to AEA CRS
p <- spTransform(p, CRS(projection(x)))

rgeos::gArea(p) * 0.000247105

par(mar = c(0, 0, 2, 0))
plot(p, main = 'SSURGO Polygons (SDA)')
```


Overlay on gSSURGO grid.
```{r}
levelplot(
  x, att = 'ID', 
  main = 'gSSURGO Grid (WCS)\nSSURGO Polygons (SDA)',
  margin = FALSE, 
  colorkey = FALSE,
  col.regions = viridis,
  panel = function(...) {
    panel.levelplot(...)
    sp.lines(p, col = 'white')
  }
)

```



# Tabular Data from SDA 

```{r}
# get unique mukeys from grid
ll <- levels(x)[[1]]

# convert into an SQL "IN" statement
IS <- format_SQL_in_statement(ll$ID)

# query SDA by mukey
sql <- sprintf("SELECT mukey, aws025wta, aws050wta, aws0100wta, aws0150wta FROM muaggatt WHERE mukey IN %s", IS)
tab <- SDA_query(sql)

```


## RAT Management
```{r}

# merge AWS by mukey into raster attribute table (RAT)
rat <- merge(ll, tab, by.x = 'ID', by.y = 'mukey', sort = FALSE, all.x = TRUE)

# re-pack RAT
levels(x) <- rat

# check: note RAT
x

# raster + RAT --> grid of values
# when more than a single attribute, result is a raster stack
# note this is a raster stack with 4 layers
(aws <- deratify(x))

# graphical check
levelplot(
  aws, 
  main = 'gNATSGO WCS + SDA',
  margin = FALSE, 
  scales = list(draw = FALSE), 
  col.regions = viridis
  )
```

## Map Unit Aggregatation Strategies


# Related WCS (ISSR-800)



```{r}
# latest from GitHub
library(soilDB)

# wrangling polygons and CRS transformations
library(sp)
library(rgdal)

# raster data visualization
library(raster)
library(rasterVis)
library(viridis)


# AOI corners in WGS84 GCS
# xmin, ymin, xmax, ymax
a <- c(-114.16, 47.65, -114.08, 47.68)

# too big for SDA geometry (>32Mb WKT serialization)
# a <- c(-114.5, 47, -114, 47.5)

# fetch gNATSGO map unit keys at native resolution
x <- mukey.wcs(var = 'gnatsgo', aoi = a)

# fetch gSSURGO map unit keys at native resolution 
# x <- mukey.wcs(var = 'gssurgo', aoi = a)

# OK
levelplot(x, att = 'ID', margin = FALSE, colorkey = FALSE, col.regions = viridis)

# convert raster extent into vector 
g <- as(extent(x), 'SpatialPolygons')
proj4string(g) <- projection(x)

# get intersecting SSURGO linework as SpatialPolygonsDataFrame from SDA
p <- SDA_spatialQuery(g, what = 'geom', geomIntersection = TRUE)

# transform to AEA CRS
p <- spTransform(p, CRS(projection(x)))

# plot together
levelplot(
  x, att = 'ID', margin = FALSE, colorkey = FALSE,
  col.regions = viridis,
  panel = function(...) {
    panel.levelplot(...)
    sp.lines(p, col = 'white')
  }
)


# thematic mapping via muaggatt table
# available water storage to several depths





## next steps
# robust / complete / fast approach for getting / aggregating / linking via SDA





```
